name: CD | Publish Package to Test PyPI

on:
  # Publish using GitHub Releases UI
  release:
    types: [published]
  # Publish using git tags
  # git tag -a v1.2.0 -m "Release v.1.2.0 - Bug fixes and improvements"
  # git push origin v1.2.0 --> triggers this workflow
  push:
    tags:
    - v*.*.*
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to (TestPyPI only for demo repo)
        required: true
        default: testpypi
        type: choice
        options:
        - testpypi
        # - pypi

permissions:
  contents: read

jobs:
  build-and-inspect:
    name: Build & inspect package.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683   # v4.2.2
      with:
        fetch-depth: 0   # Required for setuptools-scm
        persist-credentials: false
    - uses: hynek/build-and-inspect-python-package@73aea398b9d6bbe9d1310d120db0e0f4fc4b4bf7   # v2.9.0

  upload-to-test-pypi:
    name: Upload package to Test PyPI
    needs: build-and-inspect
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/nk-uv-demo/
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing, but
      # should NOT be granted anywhere else!
      id-token: write

    steps:
    - name: Download built artifact to dist/
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16   # v4.1.8
      with:
        name: Packages
        path: dist
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@f7600683efdcb7656dec5b29656edb7bc586e597   # release/v1.10.3
      with:
        repository-url: https://test.pypi.org/legacy/
