name: CD | Publish Package to Test PyPI

on:
  release:
    types: [published]
  push:
    branches:
    - main
    - release/*
    tags:
    - v*.*.*  # Only publish on semantic version tags (v1.0.0, v2.1.3, etc.)
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to (TestPyPI only for demo repo)
        required: true
        default: testpypi
        type: choice
        options:
        - testpypi
          # - pypi  # Commented out - demo repo only uses TestPyPI

permissions:
  contents: read

jobs:
  build-and-inspect-package:
    name: Build & inspect package.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0    # Required for setuptools-scm
        persist-credentials: false
    - uses: hynek/build-and-inspect-python-package@v2

  upload-to-test-pypi:
    name: Upload package to Test PyPI
    needs: build-and-inspect-package
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/nk-uv-demo/
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing, but
      # should NOT be granted anywhere else!
      id-token: write

    steps:
    - name: Download built artifact to dist/
      uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
