# https://github.com/marketplace/actions/pre-commit-uv
name: pre-commit

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: tox-dev/action-pre-commit-uv@v1
      with:
        python-version: '3.12'
