name: Test Build Only

on:
  workflow_dispatch:
  pull_request:
    paths:
    - src/**
    - pyproject.toml

permissions:
  contents: read

jobs:
  test-build:
    name: Test build & inspect package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0    # Required for setuptools-scm
        persist-credentials: false
    - uses: hynek/build-and-inspect-python-package@v2
