# https://github.com/marketplace/actions/pre-commit-uv
name: CI | Code Quality pre-commit

on:
  workflow_dispatch:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: tox-dev/action-pre-commit-uv@v1
