# Docs: https://github.com/marketplace/actions/build-and-inspect-a-python-package
name: CI | Build and Inspect a Python Package

on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]
    paths:
    - src/**
    - pyproject.toml

jobs:
  build-and-inspect-package:
    name: Build & inspect package.
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0    # Required for setuptools-scm
        persist-credentials: false
    - uses: hynek/build-and-inspect-python-package@v2
