# Docs: https://docs.safetycli.com/safety-docs/installation/securing-git-repositories/github/github-actions
name: Security Scan | Safety Scan

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
  schedule:
  - cron: 0 6 1 * *        # Monthly: 1st of month, 6 AM UTC

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        persist-credentials: false
    - name: Run Safety CLI to check for vulnerabilities
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}
