# Docs: https://docs.safetycli.com/safety-docs/installation/securing-git-repositories/github/github-actions
name: Security Scan | Safety Scan and Dependency Analysis

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
  schedule:
  - cron: 0 6 1 * *        # Monthly: 1st of month, 6 AM UTC

jobs:
  safety:
    name: Safety Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        persist-credentials: false
    - name: Run Safety CLI to check for vulnerabilities
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}

  deptry:
    name: Dependency Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    # TODO: add separate group for ci in .toml
    - name: Install dependencies
      run: uv sync --extra dev

    - name: Run deptry (dependency check)
      run: uv run deptry . --known-first-party nk_uv_demo
